[2025-02-26T19:53:09.488+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-26T19:53:09.528+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: skripsi_akhir_perbaikan.wait_for_new_data scheduled__2025-02-26T19:46:00+00:00 [queued]>
[2025-02-26T19:53:09.551+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: skripsi_akhir_perbaikan.wait_for_new_data scheduled__2025-02-26T19:46:00+00:00 [queued]>
[2025-02-26T19:53:09.552+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 6
[2025-02-26T19:53:09.594+0000] {taskinstance.py:2889} INFO - Executing <Task(SqlSensor): wait_for_new_data> on 2025-02-26 19:46:00+00:00
[2025-02-26T19:53:09.617+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=95275) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-26T19:53:09.617+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'skripsi_akhir_perbaikan', 'wait_for_new_data', 'scheduled__2025-02-26T19:46:00+00:00', '--job-id', '3564', '--raw', '--subdir', 'DAGS_FOLDER/tugas_akhir.py', '--cfg-path', '/tmp/tmpxo0apy4b']
[2025-02-26T19:53:09.620+0000] {standard_task_runner.py:72} INFO - Started process 95296 to run task
[2025-02-26T19:53:09.620+0000] {standard_task_runner.py:105} INFO - Job 3564: Subtask wait_for_new_data
[2025-02-26T19:53:09.708+0000] {task_command.py:467} INFO - Running <TaskInstance: skripsi_akhir_perbaikan.wait_for_new_data scheduled__2025-02-26T19:46:00+00:00 [running]> on host 4f74e843a221
[2025-02-26T19:53:09.852+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dion Rikki' AIRFLOW_CTX_DAG_ID='skripsi_akhir_perbaikan' AIRFLOW_CTX_TASK_ID='wait_for_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T19:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-26T19:46:00+00:00'
[2025-02-26T19:53:09.855+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-26T19:53:09.856+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-26T19:53:09.858+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_new_data state:running start_date:2025-02-26 19:53:09.529968+00:00
[2025-02-26T19:53:09.859+0000] {logging_mixin.py:190} INFO - Dag name:skripsi_akhir_perbaikan and current dag run status:running
[2025-02-26T19:53:09.860+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-26T19:53:09.885+0000] {base.py:84} INFO - Retrieving connection 'mysql_default'
[2025-02-26T19:53:09.891+0000] {sql.py:101} INFO - Poking: 
        SELECT COUNT(*) 
        FROM tugas_akhir_sensordata s
        WHERE s.timestamp >= NOW() - INTERVAL 5 MINUTE
        AND NOT EXISTS (
            SELECT 1 
            FROM fertilizer_predictions f
            WHERE CAST(f.id AS SIGNED) = s.id  -- Menggunakan SIGNED di sini
        )
     (with parameters None)
[2025-02-26T19:53:09.902+0000] {base.py:84} INFO - Retrieving connection 'mysql_default'
[2025-02-26T19:53:09.912+0000] {sql.py:553} INFO - Running statement: 
        SELECT COUNT(*) 
        FROM tugas_akhir_sensordata s
        WHERE s.timestamp >= NOW() - INTERVAL 5 MINUTE
        AND NOT EXISTS (
            SELECT 1 
            FROM fertilizer_predictions f
            WHERE CAST(f.id AS SIGNED) = s.id  -- Menggunakan SIGNED di sini
        )
    , parameters: None
[2025-02-26T19:53:09.915+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/sensors/sql.py", line 102, in poke
    records = hook.get_records(self.sql, self.parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 358, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 265, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'tugas_akhir.tugas_akhir_sensordata' doesn't exist")
[2025-02-26T19:53:09.942+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-26T19:53:09.943+0000] {logging_mixin.py:190} INFO - Task start:2025-02-26 19:53:09.529968+00:00 end:2025-02-26 19:53:09.941066+00:00 duration:0.411098
[2025-02-26T19:53:09.944+0000] {logging_mixin.py:190} INFO - Task:<Task(SqlSensor): wait_for_new_data> dag:<DAG: skripsi_akhir_perbaikan> dagrun:<DagRun skripsi_akhir_perbaikan @ 2025-02-26 19:46:00+00:00: scheduled__2025-02-26T19:46:00+00:00, state:running, queued_at: 2025-02-26 19:48:00.358957+00:00. externally triggered: False>
[2025-02-26T19:53:09.945+0000] {logging_mixin.py:190} INFO - Failure caused by (1146, "Table 'tugas_akhir.tugas_akhir_sensordata' doesn't exist")
[2025-02-26T19:53:09.947+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=skripsi_akhir_perbaikan, task_id=wait_for_new_data, run_id=scheduled__2025-02-26T19:46:00+00:00, execution_date=20250226T194600, start_date=20250226T195309, end_date=20250226T195309
[2025-02-26T19:53:09.980+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-26T19:53:09.982+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 3564 for task wait_for_new_data ((1146, "Table 'tugas_akhir.tugas_akhir_sensordata' doesn't exist"); 95296)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 306, in execute
    raise e
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 286, in execute
    poke_return = self.poke(context)
                  ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/sensors/sql.py", line 102, in poke
    records = hook.get_records(self.sql, self.parameters)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 358, in get_records
    return self.run(sql=sql, parameters=parameters, handler=fetch_all_handler)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 498, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 558, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.12/site-packages/MySQLdb/connections.py", line 265, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'tugas_akhir.tugas_akhir_sensordata' doesn't exist")
[2025-02-26T19:53:10.013+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-26T19:53:10.057+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T19:53:10.060+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
