[2025-04-21T10:55:09.124+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-21T10:55:09.698+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: perbaikan_skripsi.wait_for_new_data scheduled__2025-04-21T05:38:00+00:00 [queued]>
[2025-04-21T10:55:10.306+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: perbaikan_skripsi.wait_for_new_data scheduled__2025-04-21T05:38:00+00:00 [queued]>
[2025-04-21T10:55:10.313+0000] {taskinstance.py:2866} INFO - Starting attempt 8 of 4
[2025-04-21T10:55:12.127+0000] {taskinstance.py:2889} INFO - Executing <Task(SqlSensor): wait_for_new_data> on 2025-04-21 05:38:00+00:00
[2025-04-21T10:55:14.278+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'perbaikan_skripsi', 'wait_for_new_data', 'scheduled__2025-04-21T05:38:00+00:00', '--job-id', '9237', '--raw', '--subdir', 'DAGS_FOLDER/tugas_akhir.py', '--cfg-path', '/tmp/tmp6ykotljj']
[2025-04-21T10:55:16.023+0000] {standard_task_runner.py:105} INFO - Job 9237: Subtask wait_for_new_data
[2025-04-21T10:55:20.496+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=176) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-21T10:55:20.502+0000] {standard_task_runner.py:72} INFO - Started process 295 to run task
[2025-04-21T10:55:47.201+0000] {job.py:229} INFO - Heartbeat recovered after 43.36 seconds
[2025-04-21T10:55:58.912+0000] {task_command.py:467} INFO - Running <TaskInstance: perbaikan_skripsi.wait_for_new_data scheduled__2025-04-21T05:38:00+00:00 [running]> on host a9576c91091e
[2025-04-21T10:56:00.764+0000] {job.py:229} INFO - Heartbeat recovered after 14.73 seconds
[2025-04-21T10:56:08.244+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dion Rikki' AIRFLOW_CTX_DAG_ID='perbaikan_skripsi' AIRFLOW_CTX_TASK_ID='wait_for_new_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-21T05:38:00+00:00' AIRFLOW_CTX_TRY_NUMBER='8' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-21T05:38:00+00:00'
[2025-04-21T10:56:08.263+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-21T10:56:08.319+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-21T10:56:08.389+0000] {logging_mixin.py:190} INFO - Current task name:wait_for_new_data state:running start_date:2025-04-21 10:55:10.180565+00:00
[2025-04-21T10:56:08.416+0000] {logging_mixin.py:190} INFO - Dag name:perbaikan_skripsi and current dag run status:running
[2025-04-21T10:56:08.421+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-21T10:56:08.563+0000] {base.py:84} INFO - Retrieving connection 'mysql_default'
[2025-04-21T10:56:08.598+0000] {sql.py:101} INFO - Poking: 
            SELECT COUNT(*) 
            FROM tugas_akhir_sensordata s
            WHERE s.timestamp >= NOW() - INTERVAL 3 MINUTE
            AND s.soil_type IS NOT NULL
            AND s.crop_type IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 
                FROM fertilizer_predictions f
                WHERE f.sensor_data_id = s.id
            )
         (with parameters None)
[2025-04-21T10:56:08.657+0000] {base.py:84} INFO - Retrieving connection 'mysql_default'
[2025-04-21T10:56:08.692+0000] {sql.py:553} INFO - Running statement: 
            SELECT COUNT(*) 
            FROM tugas_akhir_sensordata s
            WHERE s.timestamp >= NOW() - INTERVAL 3 MINUTE
            AND s.soil_type IS NOT NULL
            AND s.crop_type IS NOT NULL
            AND NOT EXISTS (
                SELECT 1 
                FROM fertilizer_predictions f
                WHERE f.sensor_data_id = s.id
            )
        , parameters: None
[2025-04-21T10:56:08.712+0000] {sql.py:562} INFO - Rows affected: 1
[2025-04-21T10:56:08.725+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 18963.3765 seconds exceeds the specified timeout of 600.0.
[2025-04-21T10:56:08.998+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-21T10:56:09.047+0000] {logging_mixin.py:190} INFO - Task start:2025-04-21 10:55:10.180565+00:00 end:2025-04-21 10:56:08.991386+00:00 duration:58.810821
[2025-04-21T10:56:09.054+0000] {logging_mixin.py:190} INFO - Task:<Task(SqlSensor): wait_for_new_data> dag:<DAG: perbaikan_skripsi> dagrun:<DagRun perbaikan_skripsi @ 2025-04-21 05:38:00+00:00: scheduled__2025-04-21T05:38:00+00:00, state:running, queued_at: 2025-04-21 05:40:00.791133+00:00. externally triggered: False>
[2025-04-21T10:56:09.090+0000] {logging_mixin.py:190} INFO - Failure caused by Sensor has timed out; run duration of 18963.3765 seconds exceeds the specified timeout of 600.0.
[2025-04-21T10:56:09.117+0000] {taskinstance.py:1225} INFO - Immediate failure requested. Marking task as FAILED. dag_id=perbaikan_skripsi, task_id=wait_for_new_data, run_id=scheduled__2025-04-21T05:38:00+00:00, execution_date=20250421T053800, start_date=20250421T105510, end_date=20250421T105608
[2025-04-21T10:56:09.547+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-21T10:56:09.561+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9237 for task wait_for_new_data (Sensor has timed out; run duration of 18963.3765 seconds exceeds the specified timeout of 600.0.; 295)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/sensors/base.py", line 323, in execute
    raise AirflowSensorTimeout(message)
airflow.exceptions.AirflowSensorTimeout: Sensor has timed out; run duration of 18963.3765 seconds exceeds the specified timeout of 600.0.
[2025-04-21T10:56:10.271+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-21T10:56:12.669+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-21T10:56:13.457+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-04-21T10:56:13.859+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
